### ISSUE TITLE
High CPU usage when using pyright with PDM package manager

### ISSUE THREAD

**Issue by nyngwang** [neovim/nvim-lspconfig#1751]
### Description

**Describe the bug**
I know that pyright supports `pyproject.toml`, so I did add the following:

```toml
[tool.pyright]
extraPaths = ["__pypackages__/3.9/lib/"]
```
but I'm also using a library called [PDM](https://github.com/pdm-project/pdm).

Currently, it seems that when the pyright is resolving those packages installed in `__pypackages__/3.x/lib` the CPU usage will become very very high. And in my Activity Monitor (I"m using macOS) it's `node` that causes the problem. When I force terminated that node process then there is a message shown in my editor(I'm using neovim) that the LSP client is killed.

### Neovim version

NVIM v0.7.0-dev+1163-ga7bc3e0f7
Build type: Release
LuaJIT 2.1.0-beta3

### Nvim-lspconfig version

103bbcc

### Operating system and version

macOS 11.6.2

### Affected language servers

pyright

### Steps to reproduce

You will have to install [PDM](https://github.com/pdm-project/pdm). (In my case I install it from `brew`)

```toml
[project]
...
requires-python = ">=3.9"
dependencies = [
    "scikit-learn>=1.0.2",
    "requests>=2.27.1",
]
[tool.pyright]
extraPaths = ["__pypackages__/3.9/lib/"]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
```

### Actual behavior

There are two processes `node` shown in my activity monitor and both have CPU usage 99.9% hanging there forever.

### Expected behavior

The CPU usage should not go over 100%.

**Additional context**

### Minimal config

```Lua
use {
  'neovim/nvim-lspconfig'
}

M = {
  capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities()),
  autostart = true,
  on_attach = function (client, bufnr)
    client.resolved_capabilities.document_formatting = false
    client.resolved_capabilities.document_range_formatting = false
  end
}

return M
```

### LSP log

[WARN][2022-03-02 00:58:39] .../lua/vim/lsp.lua:812	"server_request: no handler found for"	"workspace/semanticTokens/refresh" [WARN][2022-03-02 00:58:39] .../lua/vim/lsp.lua:812	"server_request: no handler found for"	"workspace/semanticTokens/refresh" [START][2022-03-02 00:58:48] LSP logging initiated [WARN][2022-03-02 00:58:53] .../lua/vim/lsp.lua:812	"server_request: no handler found for"	"workspace/semanticTokens/refresh" [WARN][2022-03-02 00:58:53] .../lua/vim/lsp.lua:812	"server_request: no handler found for"	"workspace/semanticTokens/refresh" [WARN][2022-03-02 00:58:53] .../lua/vim/lsp.lua:812	"server_request: no handler found for"	"workspace/semanticTokens/refresh" [WARN][2022-03-02 00:58:53] .../lua/vim/lsp.lua:812	"server_request: no handler found for"	"workspace/semanticTokens/refresh"
